---
swagger: "2.0"
info:
  description: "This is the REST API for the in-situ pipeline."
  version: "1.0.0"
  title: "In-Situ Pipeline REST API"
host: "localhost"
basePath: "/"
schemes:
- "https"
- "http"
paths:
  /info:
    get:
      tags:
      - "nest"
      summary: "Retrieves general simulation information."
      operationId: "get_info"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Operation successful."
          schema:
            type: "number"
            format: "double"
        400:
          description: "Operation failed."
          schema:
            $ref: "#/definitions/Info"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
  /current_simulation_time:
    get:
      tags:
      - "nest"
      summary: "Retrieves the current simulation time."
      operationId: "get_current_simulation_time"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Operation successful."
          schema:
            type: "number"
            format: "int64"
        400:
          description: "Operation failed."
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
  /neuron_ids:
    get:
      tags:
      - "nest"
      summary: "Retrieves the list of all neuron IDs."
      operationId: "get_neuron_ids"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Operation successful."
          schema:
            type: "array"
            items:
              type: "number"
              format: "int64"
        400:
          description: "Operation failed."
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
  /attributes:
    get:
      tags:
      - "nest"
      summary: "Retrieves the details of per-neuron attributes."
      operationId: "get_attributes"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Operation successful."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Attribute"
        400:
          description: "Operation failed."
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
  /data:
    get:
      tags:
      - "nest"
      summary: "Retrieves the per-neuron attributes for the given multimeter name,\
        \ attribute name, duration (from - to) (optional) and neuron IDs (optional)."
      operationId: "get_data"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "multimeter"
        in: "query"
        description: "Multimeter name."
        required: true
        type: "string"
      - name: "attribute"
        in: "query"
        description: "Attribute name."
        required: true
        type: "string"
      - name: "from"
        in: "query"
        description: "First timestep to retreive (leave empty for first step possible)."
        required: false
        type: "number"
        collectionFormat: "multi"
        format: "double"
      - name: "to"
        in: "query"
        description: "Last timestep to retreive (leave empty for last step possible)."
        required: false
        type: "number"
        collectionFormat: "multi"
        format: "double"
      - name: "neuron_ids"
        in: "query"
        description: "Neuron IDs (leave empty for all neurons)."
        required: false
        type: "array"
        items:
          type: "number"
          format: "int64"
        collectionFormat: "multi"
      responses:
        200:
          description: "Operation successful."
          schema:
            $ref: "#/definitions/Data"
        400:
          description: "Operation failed."
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
  /spikes:
    get:
      tags:
      - "nest"
      summary: "Retrieves the spikes for the given simulation steps (optional) and\
        \ neuron IDs (optional)."
      operationId: "get_spikes"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "simulation_steps"
        in: "query"
        description: "Simulation steps (leave empty for all steps)."
        required: false
        type: "array"
        items:
          type: "number"
          format: "int64"
        collectionFormat: "multi"
      - name: "neuron_ids"
        in: "query"
        description: "Neuron IDs (leave empty for all neurons)."
        required: false
        type: "array"
        items:
          type: "number"
          format: "int64"
        collectionFormat: "multi"
      responses:
        200:
          description: "Operation successful."
          schema:
            $ref: "#/definitions/Spikes"
        400:
          description: "Operation failed."
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
definitions:
  Precision:
    type: "string"
    enum:
    - "double"
    - "integer"
  Attribute:
    type: "object"
    properties:
      name:
        type: "string"
      precision:
        $ref: "#/definitions/Precision"
    example:
      precision: {}
      name: "name"
  Multimeter:
    type: "object"
    properties:
      name:
        type: "string"
      interval:
        type: "number"
        format: "double"
      attribute:
        $ref: "#/definitions/Attribute"
      measurement_times:
        type: "array"
        items:
          type: "number"
          format: "double"
      from:
        type: "number"
        format: "double"
      to:
        type: "number"
        format: "double"
      neuron_ids:
        type: "array"
        items:
          type: "number"
          format: "int64"
      values:
        type: "array"
        items:
          type: "array"
          items:
            type: "number"
    example:
      name: "Multimeter_name"
      interval: 0.2
      attribute:
        name: "voltage"
        precission: "double"
      timesteps:
      - 1.2
      - 1.4
      from: 1.2
      to: 1.4
      neuron_ids:
      - 1
      - 2
      values:
      - - 61.48
        - 45.23
      - - 13.46
        - 23.77
  MultimeterInfo:
    type: "object"
    properties:
      name:
        type: "string"
      interval:
        type: "number"
        format: "double"
      attributes:
        type: "array"
        items:
          $ref: "#/definitions/Attribute"
  Info:
    type: "object"
    properties:
      simulation_resolution:
        type: "number"
        format: "double"
      multimeters:
        type: "array"
        items:
          $ref: "#/definitions/MultimeterInfo"
  Data:
    type: "object"
    properties:
      multimeters:
        type: "array"
        items:
          $ref: "#/definitions/Multimeter"
    example:
      multimeters:
      - name: "Multimeter_name"
        interval: 0.2
        attribute:
          name: "voltage"
          precission: "double"
        timesteps:
        - 1.2
        - 1.4
        from: 1.2
        to: 1.4
        neuron_ids:
        - 1
        - 2
        values:
        - - 61.48
          - 45.23
        - - 13.46
          - 23.77
      - name: "Multimeter_name"
        interval: 0.2
        attribute:
          name: "voltage"
          precission: "double"
        timesteps:
        - 1.2
        - 1.4
        from: 1.2
        to: 1.4
        neuron_ids:
        - 1
        - 2
        values:
        - - 61.48
          - 45.23
        - - 13.46
          - 23.77
  Spikes:
    type: "object"
    properties:
      simulation_times:
        type: "array"
        items:
          type: "number"
          format: "int64"
      neuron_ids:
        type: "array"
        items:
          type: "number"
          format: "int64"
    example:
      simulation_times:
      - 0.80082819046101150206595775671303272247314453125
      - 0.80082819046101150206595775671303272247314453125
      neuron_ids:
      - 6.02745618307040320615897144307382404804229736328125
      - 6.02745618307040320615897144307382404804229736328125
  Error:
    type: "object"
    properties:
      code:
        type: "number"
      message:
        type: "string"
