---
swagger: "2.0"
info:
  description: "This is the REST API for the in-situ pipeline."
  version: "1.0.0"
  title: "In-Situ Pipeline REST API"
host: "localhost"
basePath: "/"
schemes:
- "https"
- "http"
paths:
  /timestep:
    get:
      tags:
      - "nest"
      summary: "Retrieves the time between two simulation steps."
      operationId: "get_timestep"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Operation successful."
          schema:
            type: "number"
            format: "double"
        400:
          description: "Operation failed."
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
  /simulation_step_count:
    get:
      tags:
      - "nest"
      summary: "Retrieves the number of simulation steps."
      operationId: "get_simulation_step_count"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Operation successful."
          schema:
            type: "number"
            format: "int64"
        400:
          description: "Operation failed."
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
  /gids:
    get:
      tags:
      - "nest"
      summary: "Retrieves the list of all neuron IDs."
      operationId: "get_gids"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Operation successful."
          schema:
            type: "array"
            items:
              type: "number"
              format: "int64"
        400:
          description: "Operation failed."
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
  /spikes:
    get:
      tags:
      - "nest"
      summary: "Retrieves the spikes for the given simulation steps (optional) and\
        \ neuron IDs (optional)."
      operationId: "get_spikes"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "from"
        in: "query"
        description: "TODO"
        required: false
        type: "number"
        format: "int64"
      - name: "to"
        in: "query"
        description: "TODO"
        required: false
        type: "number"
        format: "int64"
      responses:
        200:
          description: "Operation successful."
          schema:
            $ref: "#/definitions/Spikes"
        400:
          description: "Operation failed."
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
definitions:
  Spikes:
    type: "object"
    properties:
      simulation_steps:
        type: "array"
        items:
          type: "number"
          format: "int64"
      gids:
        type: "array"
        items:
          type: "number"
          format: "int64"
    example:
      simulation_steps:
      - 2
      - 5
      gids:
      - 1
      - 2
  Error:
    type: "object"
    properties:
      code:
        type: "number"
      message:
        type: "string"