---
swagger: "2.0"
info:
  description: "This is the REST API for the in-situ pipeline."
  version: "1.0.0"
  title: "In-Situ Pipeline REST API"
host: "localhost"
basePath: "/"
schemes:
- "https"
- "http"
paths:
  /simulation_time_info:
    get:
      tags:
      - "nest"
      summary: "Retrieves the number of simulation steps."
      operationId: "get_simulation_step_count"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Operation successful."
          schema:
            $ref: "#/definitions/SimulationTimeInfo"
        400:
          description: "Operation failed."
          schema:
            type: "string"
            example: "Error message"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
  /gids:
    get:
      tags:
      - "nest"
      summary: "Retrieves the list of all GID."
      operationId: "get_gids"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Operation successful."
          schema:
            type: "array"
            items:
              type: "number"
              format: "uint64"
        400:
          description: "Operation failed."
          schema:
            type: "string"
            example: "Error message"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
  /neuron_properties:
    get:
      tags:
      - "nest"
      summary: "Retrieves the properties of the specified neurons."
      operationId: "get_neuron_properties"
      produces:
      - "application/json"
      parameters:
      - name: "gids"
        in: "query"
        description: "A list of GIDs queried for properties."
        required: false
        type: "array"
        items:
          type: "number"
          format: "uint64"
      responses:
        200:
          description: "Operation successful."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/NeuronProperties"
        400:
          description: "Operation failed."
          schema:
            type: "string"
            example: "Error message"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
  /populations:
    get:
      tags:
      - "nest"
      summary: "Retrieves the list of all populations."
      operationId: "get_populations"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Operation successful."
          schema:
            type: "array"
            items:
              type: "string"
        400:
          description: "Operation failed."
          schema:
            type: "string"
            example: "Error message"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
  /spikes:
    get:
      tags:
      - "nest"
      summary: "Retrieves the spikes for the given simulation steps (optional) and GIDS (optional)."
      operationId: "get_spikes"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "from"
        in: "query"
        description: "The start time (including) to be queried."
        required: false
        type: "number"
        format: "uint64"
      - name: "to"
        in: "query"
        description: "The end time (excluding) to be queried."
        required: false
        type: "number"
        format: "uint64"
      - name: "gids"
        in: "query"
        description: "A list of GIDs queried for spike data."
        required: false
        type: "array"
        items:
          type: "number"
          format: "uint64"
      - name: "offset"
        in: "query"
        description: "The offset into the result."
        required: false
        type: "number"
        format: "uint64"
      - name: "limit"
        in: "query"
        description: "The maximum of entries to be result."
        required: false
        type: "number"
        format: "uint64"
      responses:
        200:
          description: "Operation successful."
          schema:
            $ref: "#/definitions/Spikes"
        400:
          description: "Operation failed."
          schema:
            type: "string"
            example: "Error message"
      x-swagger-router-controller: "access_node.controllers.nest_controller"  
  /population/${population_id}/spikes:
    get:
      tags:
      - "nest"
      summary: "Retrieves the spikes for the given simulation steps (optional) and\
        \ neuron IDs (optional)."
      operationId: "get_spikes_by_population"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "population_id"
        in: "path"
        description: "The identifier of the population."
        required: true
        type: "string"
      - name: "from"
        in: "query"
        description: "The start time (including) to be queried."
        required: false
        type: "number"
        format: "uint64"
      - name: "to"
        in: "query"
        description: "The end time (excluding) to be queried."
        required: false
        type: "number"
        format: "uint64"
      - name: "offset"
        in: "query"
        description: "The offset into the result."
        required: false
        type: "number"
        format: "uint64"
      - name: "limit"
        in: "query"
        description: "The maximum of entries to be result."
        required: false
        type: "number"
        format: "uint64"
      responses:
        200:
          description: "Operation successful."
          schema:
            $ref: "#/definitions/Spikes"
        400:
          description: "Operation failed."
          schema:
            type: "string"
            example: "Error message"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
  /population/${population_id}/gids:
    get:
      tags:
      - "nest"
      summary: "Retrieves the list of all neuron IDs."
      operationId: "get_gids_in_population"
      produces:
      - "application/json"
      parameters: 
      - name: "population_id"
        in: "path"
        description: "The identifier of the population"
        required: true
        type: "string"
      responses:
        200:
          description: "Operation successful."
          schema:
            type: "array"
            items:
              type: "number"
              format: "uint64"
        400:
          description: "Operation failed."
          schema:
            type: "string"
            example: "Error message"
      x-swagger-router-controller: "access_node.controllers.nest_controller"
definitions:
  Spikes:
    type: "object"
    properties:
      simulation_steps:
        description: "This array is always sorted."
        type: "array"
        items:
          type: "number"
          format: "uint64"
      gids:
        type: "array"
        items:
          type: "number"
          format: "uint64"
  NeuronProperties:
    type: "object"
    properties:
      gid:
        type: "number"
        format: "uint64"
      properties:
        type: "object"
    example:
      population: "pop1"
      position: [0.1, 0.1, 0.1]
  SimulationTimeInfo:
    type: "object"
    properties:
      start:
        type: "number"
        format: "uint64"
      end:
        type: "number"
        format: "uint64"
      current:
        type: "number"
        format: "uint64"
      timestep:
        type: "number"
        format: "double"