deploy:develop:
    tags:
        - docker
        - centos
    only:
        - develop
    script:
        - docker build -t rwthvr/insite-database:develop .
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker push rwthvr/insite-database:develop

deploy:master:
    tags:
        - docker
        - centos
    only:
        - master
    script:
        - docker build -t rwthvr/insite-database .
        - VERSION=$(git tag --points-at $CI_COMMIT_SHA)
        - >
            [[ $VERSION =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]
        - docker tag rwthvr/insite-database rwthvr/insite-database:$VERSION
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker push rwthvr/insite-database
