# include:
#     - 'access-node/.gitlab-ci.yml'
#     - 'nest-module/.gitlab-ci.yml'

# stages:
#     - build
    # - test
    # - deploy

test:
  tags: 
    - shell-runner
  variables:
      GIT_SUBMODULE_STRATEGY: recursive
  script:
    - curl -L "https://github.com/docker/compose/releases/download/2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o ./docker-compose
    - chmod +x docker-compose
    - docker build . -f ./docker/simulators/Dockerfile_TVB -t insite-tvb
    - docker build . -f ./docker/simulators/Dockerfile_Arbor -t insite-arbor
    - docker build . -f ./docker/simulators/Dockerfile_NEST -t insite-nest
    - docker-compose -f ./test/run-tests.yml up --build --exit-code-from pytest

# build:
#     stage: build
#     image: registry.git-ce.rwth-aachen.de/vr-vis/vr-group/in-situ-pipeline/insite/base:latest
#     tags:
#         - docker-runner
#     variables:
#         GIT_SUBMODULE_STRATEGY: recursive
#     artifacts:
#         paths:
#         - build_access_node
#         - build_nest_module
#         expire_in: 1 day
#         when: always
#     script:
#         - mkdir build_nest_module
#         - cd build_nest_module
#         - cmake -G Ninja -Dwith-nest=/opt/nest/bin/nest-config ../nest-module/src
#         - ninja install
#
#         - cd .. && mkdir build_access_node && cd build_access_node
#         - cmake -G Ninja ../access-node
#         - ninja insite-access-node
#
# test:
#     stage: test
#     image: registry.git-ce.rwth-aachen.de/vr-vis/vr-group/in-situ-pipeline/insite/base:latest
#     tags:
#         - docker-runner
#     variables:
#         GIT_SUBMODULE_STRATEGY: recursive
#
#     artifacts:
#         paths:
#         - build_access_node
#         - build_nest_module
#         - insite.log
#         - access_node.log
#         expire_in: 1 day
#         when: always
#     before_script:
#         - pip3 install -r test/test-requirements.txt
#         - cd build_nest_module
#         - ninja install
#         - cd ..
#         - cp build_access_node/insite-access-node .
#     script:
#         - pytest --count=2 --repeat-scope=session -x --showlocals ./test -s
#         # - pytest --count=2 --repeat-scope=session -x --showlocals --ignore-glob=**/_deps/* --ignore-glob=**/extern/* -s
#
