include:
    - project: 'vr-group/in-situ-pipeline/insite'
      ref: develop
      file: '/test-setup.yml'

variables:
    INSITE_NEST_MODULE_COMMIT: $CI_COMMIT_SHA

# api_test:
#     extends: .api_test

deploy:
    tags:
        - docker
        - centos
    only:
        - develop
    script:
        - docker build -t rwthvr/insite-nest-module:develop .
        - echo ${DOCKER_USERNAME}
        - docker login hub.docker.com -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker push rwthvr/insite-nest-module:develop
