# include:
#     - 'access-node/.gitlab-ci.yml'
#     - 'nest-module/.gitlab-ci.yml'

stages:
    - test
    # - deploy

test:
    image: insite/base
    tags:
        - docker-executor
    artifacts:
        paths:
        - docker-compose.log
        expire_in: 1 week
        when: always
    script:
        - pip3 install --user -r test-requirements.txt
        - mkdir build
        - cd build
        - cmake -G Ninja -Dwith-nest=/opt/nest/bin/nest-config ..
        - ninja install
