variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - pip3 install -r swagger_doc_requirements.txt

build_api_reference:
  tags:
    - centos
    - docker
  script:
    - mkdir doc
    - cd doc
    - rm -rf *
    - python3 ../swagger_doc.py ../access-node/access_node/swagger/swagger.yaml
    - git add -u
    - git add .
    - git status
