variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - pip3 install -r swagger_doc_requirements.txt

build_api_reference:
  tags:
    - centos
    - docker
  script:
    - git clone https://oauth2:$ACCESS_TOKEN@devhub.vr.rwth-aachen.de/VR-Group/in-situ-pipeline/insite.wiki.git
    - cd insite.wiki
    - rm -rf *
    - python3 ../swagger_doc.py ../access-node/access_node/swagger/swagger.yaml
    - git add -u
    - git add .
    - git status
