stages:
    - build
    - test
    - deploy

build:
  stage: build
  tags: 
    - shell-runner
  variables:
      GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-linux-x86_64" -o ./docker-compose
    - chmod +x docker-compose

  script:
    - docker build . -f ./docker/simulators/Dockerfile_TVB -t insite-tvb
    - docker build . -f ./docker/simulators/Dockerfile_Arbor -t insite-arbor
    - docker build . -f ./docker/simulators/Dockerfile_NEST -t insite-nest
    - docker build . -f ./docker/Dockerfile_AccessNode -t insite-access-node
    - docker build . -f ./docker/examples/Dockerfile_TVBExample -t insite-tvb-example
    - docker build . -f ./docker/examples/Dockerfile_NestExample -t insite-nest-example
    - docker build . -f ./docker/examples/Dockerfile_ArborRingExample -t insite-arbor-example-ring
    - docker compose -f ./test/run-tests.yml up --build --exit-code-from pytest

deploy:
  stage: deploy
  tags: 
    - shell-runner
  variables:
      GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - echo $REGISTRY_TOKEN | docker login -u "robot$insite+registry_pusher" --password-stdin  registry.git-ce.rwth-aachen.de
  script:
    - docker build . -f ./docker/simulators/Dockerfile_TVB -t insite-tvb:CI-Test
    # - docker build . -f ./docker/simulators/Dockerfile_Arbor -t insite-arbor
    # - docker build . -f ./docker/simulators/Dockerfile_NEST -t insite-nest
    # - docker build . -f ./docker/Dockerfile_AccessNode -t insite-access-node
    # - docker build . -f ./docker/examples/Dockerfile_TVBExample -t insite-tvb-example
    # - docker build . -f ./docker/examples/Dockerfile_NestExample -t insite-nest-example
    # - docker build . -f ./docker/examples/Dockerfile_ArborRingExample -t insite-arbor-example-ring
    #
    # - docker tag insite-access-node docker-registry.ebrains.eu/insite/insite-access-node
    - docker tag insite-tvb docker-registry.ebrains.eu/insite/insite-tvb:CI-Test
    # - docker tag insite-arbor docker-registry.ebrains.eu/insite/insite-arbor
    # - docker tag insite-nest docker-registry.ebrains.eu/insite/insite-nest
    # - docker tag insite-nest-example docker-registry.ebrains.eu/insite/insite-nest-example
    # - docker tag insite-arbor-example docker-registry.ebrains.eu/insite/insite-arbor-example
    # - docker tag insite-arbor-example docker-registry.ebrains.eu/insite/insite-arbor-example-ring
    # - docker tag insite-tvb-example docker-registry.ebrains.eu/insite/insite-tvb-example
    # - docker push docker-registry.ebrains.eu/insite/insite-access-node
    # - docker push docker-registry.ebrains.eu/insite/insite-tvb
    # - docker push docker-registry.ebrains.eu/insite/insite-arbor
    # - docker push docker-registry.ebrains.eu/insite/insite-nest
    # - docker push docker-registry.ebrains.eu/insite/insite-tvb-example
    # - docker push docker-registry.ebrains.eu/insite/insite-arbor-example
    # - docker push docker-registry.ebrains.eu/insite/insite-arbor-example-ring
    # - docker push docker-registry.ebrains.eu/insite/insite-nest-example

