include:
    - project: 'vr-group/in-situ-pipeline/insite'
      ref: add-test-pipeline 
      file: '/test-setup.yml'

variables:
    INSITE_NEST_MODULE_COMMIT: $CI_COMMIT_SHA

api_test:
    extends: .api_test
