version: "3"

services:
  insite-access-node:
    build: ./access-node
    ports:
      - "8080:8080"
    depends_on:
      - "insite-nest-module"
    command: ["http://insite-nest-module:9000"]

  insite-nest-module:
    build: ./nest-module
    ports:
      - "5000:5000"
      - "9000-9005:9000-9005"
    environment:
      INSITE_DOCKER_USE_NEST_SERVER: 1
