version: '3'
services:
  database:
    image: postgres:12.1
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'docker'
      - POSTGRES_DB:'postgres'
    container_name: "insite_pg-database"
    ports:
      - "5432:5432"
  access-node:
    build: ./access-node
    ports:
      - "8080:8080"
    depends_on:
    - "database"
  insite-nest-module:
    build: ./insite-nest-module
    entrypoint:
    - "/insite/wait-for.sh"
    - "-t"
    - "5"
    - "database:5432"
    - "--"
    - "/insite-build/run_brunel_simulation.sh"
    - "1000"
    depends_on:
    - "access-node"
    ports:
      - "8000:8000"
