version: "3"

services:
  insite-access-node:
    image:
      registry.git-ce.rwth-aachen.de/vr-vis/vr-group/in-situ-pipeline/insite/insite-access-node
    ports:
      - "52056:52056" # depends_on:
      - "9011:9011" # depends_on:
    environment:
      INSITE_NEST_BASE_URL: "insite-nest-module"
      INSITE_ARBOR_BASE_URL: "arbor-module"

  nest-example:
    image:
      registry.git-ce.rwth-aachen.de/vr-vis/vr-group/in-situ-pipeline/insite/insite-nest-example

  tvb-example: 
    image:
      registry.git-ce.rwth-aachen.de/vr-vis/vr-group/in-situ-pipeline/insite/insite-tvb-example
    environment:
      INSITE_ACCESS_NODE_URL: "insite-access-node"
    depends_on:
      - insite-access-node

  arbor-example: 
    image:
      registry.git-ce.rwth-aachen.de/vr-vis/vr-group/in-situ-pipeline/insite/insite-arbor-example
    depends_on:
      - insite-access-node
