version: '3'
services:
  # access-node:
  #   build: ./access-node
  #   ports:
  #     - "8079:8079"
  info-node:
    build: ./info-node
    ports:
      - "8080:8080"
  insite-nest-module:
    build: ./insite-nest-module
    entrypoint:
    - "/insite/wait-for.sh"
    - "-t"
    - "5"
    - "info-node:8080"
    - "--"
    - "/insite-build/run_brunel_simulation.sh"
    - "1000"
    depends_on:
    # - "access-node"
    - "info-node"
    ports:
      - "8000:8000"
