version: "3"

services:
  insite-access-node:
    image: registry.git-ce.rwth-aachen.de/vr-vis/vr-group/in-situ-pipeline/insite/access_node:arbor
    ports:
      - "52056:52056"
    depends_on:
      - "insite-nest-module"
    environment:
      INSITE_NEST_BASE_URL: "insite-nest-module"
      INSITE_ARBOR_BASE_URL: "arbor-module"
    # volumes:
    #   - ${PWD}/config.toml:/config.toml

  nest-desktop:
    image: docker-registry.ebrains.eu/nest/nest-desktop:3.2
    environment:
      NEST_SIMULATOR_PORT: 52425
    ports:
      - '54286:54286'

  insite-nest-module:
    image: docker-registry.ebrains.eu/insite/nest_module:3.4_rc_latest
    ports:
      - "18080:18080"
      - "52425:52425"
    environment:
      NEST_CONTAINER_MODE: "nest-server"

  arbor-module: 
    image: registry.git-ce.rwth-aachen.de/vr-vis/vr-group/in-situ-pipeline/insite/insite-arbor
    ports:
      - "1337:1337"