deploy:nest-module:develop:
    stage: deploy
    tags:
        - docker
        - centos
    only:
        - develop
    script:
        - docker build -t rwthvr/insite-nest-module:develop nest-module
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker push rwthvr/insite-nest-module:develop

deploy:nest-module:master:
    stage: deploy
    tags:
        - docker
        - centos
    only:
        - master
    script:
        - docker build -t rwthvr/insite-nest-module nest-module
        - VERSION=$(git tag --points-at $CI_COMMIT_SHA)
        - >
            [[ $VERSION =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]
        - docker tag rwthvr/insite-nest-module rwthvr/insite-nest-module:$VERSION
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker push rwthvr/insite-nest-module
