from enum import Enum

#Base URL and prefix for every HTTP-querie to the Arbor-Server
BASE_REQUEST_URL = "http://insite-access-node:52056/arbor"

#Relates every value to its corresponding name in the spike-data JSON-field
class JSON_VALUE_TO_FIELD_NAME(Enum):
    simulationTimes = "simulationTimes"
    gIds = "gIds"
    spikerecorderId = "spikerecorderId"
    spikerecorders = "spikerecorders"
    spikes = "spikes"
    lastFrame = "lastFrame"
    simulationId = "simId"
    nodeCollections = "nodeCollections"
    kernelStatuses = "kernelStatuses"
    probeData = "probeData"
    probeKind = "probeKind"
    cellInfos = "CellInfos"
    probes = "probes"
    globalProbeIndex = "globalProbeIndex"
    cells = "cells"
    cellGid = "cellGid"
    cellLid = "cellLid"
    sourceIndex = "sourceIndex"
    cellDescription = "cellDescription"
    gid = "gid"
    lid = "lid"
    cellKind = "cellKind"
    numBranches = "numBranches"
    numSegments = "numSegments"
    size = "size"
    time = "time"
    data = "data"
    morphology = "morphology"
    label = "label"
    decor = "decor"
    location = "location"
    hash = "hash"
    toTime = "toTime"
    fromTime = "fromTime"
