FROM docker-registry.ebrains.eu/nest/nest-simulator:3.4

RUN apt-get update && apt-get install -y git ninja-build libssl-dev libfmt-dev libspdlog-dev
COPY ./nest-module/ ./nest-module

WORKDIR build_nest_module

RUN cmake -G Ninja -Dwith-nest=/opt/nest/bin/nest-config ../nest-module/src -DSPDLOG_INSTALL=ON
RUN ninja install

FROM docker-registry.ebrains.eu/nest/nest-simulator:3.4

RUN apt-get update && apt-get install -y libssl-dev libfmt-dev libspdlog-dev 

COPY --from=0 /opt/nest/lib/nest/ /opt/nest/lib/nest/
