# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from access_node.models.base_model_ import Model
from access_node.models.inner_error import InnerError
from access_node import util

from access_node.models.inner_error import InnerError  # noqa: E501

class Error(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, message=None, innererror=None):  # noqa: E501
        """Error - a model defined in OpenAPI

        :param code: The code of this Error.  # noqa: E501
        :type code: str
        :param message: The message of this Error.  # noqa: E501
        :type message: str
        :param innererror: The innererror of this Error.  # noqa: E501
        :type innererror: InnerError
        """
        self.openapi_types = {
            'code': str,
            'message': str,
            'innererror': InnerError
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'innererror': 'innererror'
        }

        self._code = code
        self._message = message
        self._innererror = innererror

    @classmethod
    def from_dict(cls, dikt) -> 'Error':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Error of this Error.  # noqa: E501
        :rtype: Error
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this Error.

        One of the error codes defined here: [...]  # noqa: E501

        :return: The code of this Error.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this Error.

        One of the error codes defined here: [...]  # noqa: E501

        :param code: The code of this Error.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self):
        """Gets the message of this Error.

        A human-readable representation of the error.  # noqa: E501

        :return: The message of this Error.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this Error.

        A human-readable representation of the error.  # noqa: E501

        :param message: The message of this Error.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def innererror(self):
        """Gets the innererror of this Error.


        :return: The innererror of this Error.
        :rtype: InnerError
        """
        return self._innererror

    @innererror.setter
    def innererror(self, innererror):
        """Sets the innererror of this Error.


        :param innererror: The innererror of this Error.
        :type innererror: InnerError
        """

        self._innererror = innererror
