# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from access_node.models.base_model_ import Model
from access_node import util


class MultimeterMeasurement(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, simulation_times=None, node_ids=None, values=None):  # noqa: E501
        """MultimeterMeasurement - a model defined in OpenAPI

        :param simulation_times: The simulation_times of this MultimeterMeasurement.  # noqa: E501
        :type simulation_times: List[float]
        :param node_ids: The node_ids of this MultimeterMeasurement.  # noqa: E501
        :type node_ids: List[int]
        :param values: The values of this MultimeterMeasurement.  # noqa: E501
        :type values: List[float]
        """
        self.openapi_types = {
            'simulation_times': List[float],
            'node_ids': List[int],
            'values': List[float]
        }

        self.attribute_map = {
            'simulation_times': 'simulationTimes',
            'node_ids': 'nodeIds',
            'values': 'values'
        }

        self._simulation_times = simulation_times
        self._node_ids = node_ids
        self._values = values

    @classmethod
    def from_dict(cls, dikt) -> 'MultimeterMeasurement':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MultimeterMeasurement of this MultimeterMeasurement.  # noqa: E501
        :rtype: MultimeterMeasurement
        """
        return util.deserialize_model(dikt, cls)

    @property
    def simulation_times(self):
        """Gets the simulation_times of this MultimeterMeasurement.

        This array is always sorted.  # noqa: E501

        :return: The simulation_times of this MultimeterMeasurement.
        :rtype: List[float]
        """
        return self._simulation_times

    @simulation_times.setter
    def simulation_times(self, simulation_times):
        """Sets the simulation_times of this MultimeterMeasurement.

        This array is always sorted.  # noqa: E501

        :param simulation_times: The simulation_times of this MultimeterMeasurement.
        :type simulation_times: List[float]
        """

        self._simulation_times = simulation_times

    @property
    def node_ids(self):
        """Gets the node_ids of this MultimeterMeasurement.


        :return: The node_ids of this MultimeterMeasurement.
        :rtype: List[int]
        """
        return self._node_ids

    @node_ids.setter
    def node_ids(self, node_ids):
        """Sets the node_ids of this MultimeterMeasurement.


        :param node_ids: The node_ids of this MultimeterMeasurement.
        :type node_ids: List[int]
        """

        self._node_ids = node_ids

    @property
    def values(self):
        """Gets the values of this MultimeterMeasurement.

        This array contains the measured values for each node ID and time to get the value for node ID n at time t you have to use the index n * length(simulationTimes) + t  # noqa: E501

        :return: The values of this MultimeterMeasurement.
        :rtype: List[float]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this MultimeterMeasurement.

        This array contains the measured values for each node ID and time to get the value for node ID n at time t you have to use the index n * length(simulationTimes) + t  # noqa: E501

        :param values: The values of this MultimeterMeasurement.
        :type values: List[float]
        """

        self._values = values
