# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from access_node.models.base_model_ import Model
from access_node import util


class SimulationTimeInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, step_size=None, begin=None, end=None, current=None):  # noqa: E501
        """SimulationTimeInfo - a model defined in OpenAPI

        :param step_size: The step_size of this SimulationTimeInfo.  # noqa: E501
        :type step_size: float
        :param begin: The begin of this SimulationTimeInfo.  # noqa: E501
        :type begin: float
        :param end: The end of this SimulationTimeInfo.  # noqa: E501
        :type end: float
        :param current: The current of this SimulationTimeInfo.  # noqa: E501
        :type current: float
        """
        self.openapi_types = {
            'step_size': float,
            'begin': float,
            'end': float,
            'current': float
        }

        self.attribute_map = {
            'step_size': 'stepSize',
            'begin': 'begin',
            'end': 'end',
            'current': 'current'
        }

        self._step_size = step_size
        self._begin = begin
        self._end = end
        self._current = current

    @classmethod
    def from_dict(cls, dikt) -> 'SimulationTimeInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SimulationTimeInfo of this SimulationTimeInfo.  # noqa: E501
        :rtype: SimulationTimeInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def step_size(self):
        """Gets the step_size of this SimulationTimeInfo.


        :return: The step_size of this SimulationTimeInfo.
        :rtype: float
        """
        return self._step_size

    @step_size.setter
    def step_size(self, step_size):
        """Sets the step_size of this SimulationTimeInfo.


        :param step_size: The step_size of this SimulationTimeInfo.
        :type step_size: float
        """

        self._step_size = step_size

    @property
    def begin(self):
        """Gets the begin of this SimulationTimeInfo.


        :return: The begin of this SimulationTimeInfo.
        :rtype: float
        """
        return self._begin

    @begin.setter
    def begin(self, begin):
        """Sets the begin of this SimulationTimeInfo.


        :param begin: The begin of this SimulationTimeInfo.
        :type begin: float
        """

        self._begin = begin

    @property
    def end(self):
        """Gets the end of this SimulationTimeInfo.


        :return: The end of this SimulationTimeInfo.
        :rtype: float
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this SimulationTimeInfo.


        :param end: The end of this SimulationTimeInfo.
        :type end: float
        """

        self._end = end

    @property
    def current(self):
        """Gets the current of this SimulationTimeInfo.


        :return: The current of this SimulationTimeInfo.
        :rtype: float
        """
        return self._current

    @current.setter
    def current(self, current):
        """Sets the current of this SimulationTimeInfo.


        :param current: The current of this SimulationTimeInfo.
        :type current: float
        """

        self._current = current
