# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from access_node.models.base_model_ import Model
from access_node import util


class SimulationTimeInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, begin: float=None, end: float=None, current: float=None, step_size:float=None):  # noqa: E501
        """SimulationTimeInfo - a model defined in Swagger

        :param begin: The begin of this SimulationTimeInfo.  # noqa: E501
        :type begin: float
        :param end: The end of this SimulationTimeInfo.  # noqa: E501
        :type end: float
        :param current: The current of this SimulationTimeInfo.  # noqa: E501
        :type current: float
        :param step_size: The duration of one step in milliseconds.  # noqa: E501
        :type step_size: float
        """
        self.swagger_types = {
            'begin': float,
            'end': float,
            'current': float,
            'step_size': float
        }

        self.attribute_map = {
            'begin': 'begin',
            'end': 'end',
            'current': 'current',
            'step_size': 'step_size'
        }

        self._begin = begin
        self._end = end
        self._current = current
        self._step_size = step_size

    @classmethod
    def from_dict(cls, dikt) -> 'SimulationTimeInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SimulationTimeInfo of this SimulationTimeInfo.  # noqa: E501
        :rtype: SimulationTimeInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def begin(self) -> float:
        """Gets the begin of this SimulationTimeInfo.


        :return: The begin of this SimulationTimeInfo.
        :rtype: float
        """
        return self._begin

    @begin.setter
    def begin(self, begin: float):
        """Sets the begin of this SimulationTimeInfo.


        :param begin: The begin of this SimulationTimeInfo.
        :type begin: float
        """

        self._begin = begin

    @property
    def end(self) -> float:
        """Gets the end of this SimulationTimeInfo.


        :return: The end of this SimulationTimeInfo.
        :rtype: float
        """
        return self._end

    @end.setter
    def end(self, end: float):
        """Sets the end of this SimulationTimeInfo.


        :param end: The end of this SimulationTimeInfo.
        :type end: float
        """

        self._end = end

    @property
    def current(self) -> float:
        """Gets the current of this SimulationTimeInfo.


        :return: The current of this SimulationTimeInfo.
        :rtype: float
        """
        return self._current

    @current.setter
    def current(self, current: float):
        """Sets the current of this SimulationTimeInfo.


        :param current: The current of this SimulationTimeInfo.
        :type current: float
        """

        self._current = current

    @property
    def step_size(self) -> float:
        """Gets the step_size of this SimulationTimeInfo.


        :return: The step_size of this SimulationTimeInfo.
        :rtype: float
        """
        return self._step_size

    @step_size.setter
    def step_size(self, step_size: float):
        """Sets the step_size of this SimulationTimeInfo.


        :param step_size: The step_size of this SimulationTimeInfo.
        :type step_size: float
        """

        self._step_size = step_size
