# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from access_node.models.base_model_ import Model
from access_node import util


class SpikedetectorInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, neuron_ids=None):  # noqa: E501
        """SpikedetectorInfo - a model defined in OpenAPI

        :param id: The id of this SpikedetectorInfo.  # noqa: E501
        :type id: int
        :param neuron_ids: The neuron_ids of this SpikedetectorInfo.  # noqa: E501
        :type neuron_ids: List[int]
        """
        self.openapi_types = {
            'id': int,
            'neuron_ids': List[int]
        }

        self.attribute_map = {
            'id': 'id',
            'neuron_ids': 'neuronIds'
        }

        self._id = id
        self._neuron_ids = neuron_ids

    @classmethod
    def from_dict(cls, dikt) -> 'SpikedetectorInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SpikedetectorInfo of this SpikedetectorInfo.  # noqa: E501
        :rtype: SpikedetectorInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this SpikedetectorInfo.


        :return: The id of this SpikedetectorInfo.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SpikedetectorInfo.


        :param id: The id of this SpikedetectorInfo.
        :type id: int
        """

        self._id = id

    @property
    def neuron_ids(self):
        """Gets the neuron_ids of this SpikedetectorInfo.


        :return: The neuron_ids of this SpikedetectorInfo.
        :rtype: List[int]
        """
        return self._neuron_ids

    @neuron_ids.setter
    def neuron_ids(self, neuron_ids):
        """Sets the neuron_ids of this SpikedetectorInfo.


        :param neuron_ids: The neuron_ids of this SpikedetectorInfo.
        :type neuron_ids: List[int]
        """

        self._neuron_ids = neuron_ids
