# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from access_node.models.base_model_ import Model
from access_node import util


class ArborNeuronProperties(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, neuron_id: int=None, properties: object=None):  # noqa: E501
        """ArborNeuronProperties - a model defined in Swagger

        :param neuron_id: The neuron_id of this ArborNeuronProperties.  # noqa: E501
        :type neuron_id: int
        :param properties: The properties of this ArborNeuronProperties.  # noqa: E501
        :type properties: object
        """
        self.swagger_types = {
            'neuron_id': int,
            'properties': object
        }

        self.attribute_map = {
            'neuron_id': 'neuron_id',
            'properties': 'properties'
        }

        self._neuron_id = neuron_id
        self._properties = properties

    @classmethod
    def from_dict(cls, dikt) -> 'ArborNeuronProperties':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ArborNeuronProperties of this ArborNeuronProperties.  # noqa: E501
        :rtype: ArborNeuronProperties
        """
        return util.deserialize_model(dikt, cls)

    @property
    def neuron_id(self) -> int:
        """Gets the neuron_id of this ArborNeuronProperties.


        :return: The neuron_id of this ArborNeuronProperties.
        :rtype: int
        """
        return self._neuron_id

    @neuron_id.setter
    def neuron_id(self, neuron_id: int):
        """Sets the neuron_id of this ArborNeuronProperties.


        :param neuron_id: The neuron_id of this ArborNeuronProperties.
        :type neuron_id: int
        """

        self._neuron_id = neuron_id

    @property
    def properties(self) -> object:
        """Gets the properties of this ArborNeuronProperties.


        :return: The properties of this ArborNeuronProperties.
        :rtype: object
        """
        return self._properties

    @properties.setter
    def properties(self, properties: object):
        """Sets the properties of this ArborNeuronProperties.


        :param properties: The properties of this ArborNeuronProperties.
        :type properties: object
        """

        self._properties = properties
