# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from access_node.models.base_model_ import Model
from access_node.models.precision import Precision  # noqa: F401,E501
from access_node import util


class Attribute(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, precision: Precision=None):  # noqa: E501
        """Attribute - a model defined in Swagger

        :param name: The name of this Attribute.  # noqa: E501
        :type name: str
        :param precision: The precision of this Attribute.  # noqa: E501
        :type precision: Precision
        """
        self.swagger_types = {
            'name': str,
            'precision': Precision
        }

        self.attribute_map = {
            'name': 'name',
            'precision': 'precision'
        }

        self._name = name
        self._precision = precision

    @classmethod
    def from_dict(cls, dikt) -> 'Attribute':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Attribute of this Attribute.  # noqa: E501
        :rtype: Attribute
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Attribute.


        :return: The name of this Attribute.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Attribute.


        :param name: The name of this Attribute.
        :type name: str
        """

        self._name = name

    @property
    def precision(self) -> Precision:
        """Gets the precision of this Attribute.


        :return: The precision of this Attribute.
        :rtype: Precision
        """
        return self._precision

    @precision.setter
    def precision(self, precision: Precision):
        """Sets the precision of this Attribute.


        :param precision: The precision of this Attribute.
        :type precision: Precision
        """

        self._precision = precision
