# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from access_node.models.base_model_ import Model
from access_node.models.multimeter import Multimeter  # noqa: F401,E501
from access_node import util


class Data(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, multimeters: List[Multimeter]=None):  # noqa: E501
        """Data - a model defined in Swagger

        :param multimeters: The multimeters of this Data.  # noqa: E501
        :type multimeters: List[Multimeter]
        """
        self.swagger_types = {
            'multimeters': List[Multimeter]
        }

        self.attribute_map = {
            'multimeters': 'multimeters'
        }

        self._multimeters = multimeters

    @classmethod
    def from_dict(cls, dikt) -> 'Data':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Data of this Data.  # noqa: E501
        :rtype: Data
        """
        return util.deserialize_model(dikt, cls)

    @property
    def multimeters(self) -> List[Multimeter]:
        """Gets the multimeters of this Data.


        :return: The multimeters of this Data.
        :rtype: List[Multimeter]
        """
        return self._multimeters

    @multimeters.setter
    def multimeters(self, multimeters: List[Multimeter]):
        """Sets the multimeters of this Data.


        :param multimeters: The multimeters of this Data.
        :type multimeters: List[Multimeter]
        """

        self._multimeters = multimeters
