# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from access_node.models.base_model_ import Model
from access_node import util


class MultimeterMeasurement(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, simulation_times: List[float]=None, probe_ids: List[int]=None, values: List[float]=None):  # noqa: E501
        """MultimeterMeasurement - a model defined in Swagger

        :param simulation_times: The simulation_times of this MultimeterMeasurement.  # noqa: E501
        :type simulation_times: List[float]
        :param probe_ids: The probe_ids of this MultimeterMeasurement.  # noqa: E501
        :type probe_ids: List[int]
        :param values: The values of this MultimeterMeasurement.  # noqa: E501
        :type values: List[float]
        """
        self.swagger_types = {
            'simulation_times': List[float],
            'probe_ids': List[int],
            'values': List[float]
        }

        self.attribute_map = {
            'simulation_times': 'simulation_times',
            'probe_ids': 'probe_ids',
            'values': 'values'
        }

        self._simulation_times = simulation_times
        self._probe_ids = probe_ids
        self._values = values

    @classmethod
    def from_dict(cls, dikt) -> 'MultimeterMeasurement':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MultimeterMeasurement of this MultimeterMeasurement.  # noqa: E501
        :rtype: MultimeterMeasurement
        """
        return util.deserialize_model(dikt, cls)

    @property
    def simulation_times(self) -> List[float]:
        """Gets the simulation_times of this MultimeterMeasurement.

        This array is always sorted.  # noqa: E501

        :return: The simulation_times of this MultimeterMeasurement.
        :rtype: List[float]
        """
        return self._simulation_times

    @simulation_times.setter
    def simulation_times(self, simulation_times: List[float]):
        """Sets the simulation_times of this MultimeterMeasurement.

        This array is always sorted.  # noqa: E501

        :param simulation_times: The simulation_times of this MultimeterMeasurement.
        :type simulation_times: List[float]
        """

        self._simulation_times = simulation_times

    @property
    def probe_ids(self) -> List[int]:
        """Gets the probe_ids of this MultimeterMeasurement.


        :return: The probe_ids of this MultimeterMeasurement.
        :rtype: List[int]
        """
        return self._probe_ids

    @probe_ids.setter
    def probe_ids(self, probe_ids: List[int]):
        """Sets the probe_ids of this MultimeterMeasurement.


        :param probe_ids: The probe_ids of this MultimeterMeasurement.
        :type probe_ids: List[int]
        """

        self._probe_ids = probe_ids

    @property
    def values(self) -> List[float]:
        """Gets the values of this MultimeterMeasurement.

        This array contains the measured values for each probe and time to get the value for probe n at time t you have to use the index n * length(simulation_times) + t  # noqa: E501

        :return: The values of this MultimeterMeasurement.
        :rtype: List[float]
        """
        return self._values

    @values.setter
    def values(self, values: List[float]):
        """Sets the values of this MultimeterMeasurement.

        This array contains the measured values for each probe and time to get the value for probe n at time t you have to use the index n * length(simulation_times) + t  # noqa: E501

        :param values: The values of this MultimeterMeasurement.
        :type values: List[float]
        """

        self._values = values
