# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from access_node.models.base_model_ import Model
from access_node import util


class NestNeuronProperties(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, gid: int=None, properties: object=None):  # noqa: E501
        """NestNeuronProperties - a model defined in Swagger

        :param gid: The gid of this NestNeuronProperties.  # noqa: E501
        :type gid: int
        :param properties: The properties of this NestNeuronProperties.  # noqa: E501
        :type properties: object
        """
        self.swagger_types = {
            'gid': int,
            'properties': object
        }

        self.attribute_map = {
            'gid': 'gid',
            'properties': 'properties'
        }

        self._gid = gid
        self._properties = properties

    @classmethod
    def from_dict(cls, dikt) -> 'NestNeuronProperties':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NestNeuronProperties of this NestNeuronProperties.  # noqa: E501
        :rtype: NestNeuronProperties
        """
        return util.deserialize_model(dikt, cls)

    @property
    def gid(self) -> int:
        """Gets the gid of this NestNeuronProperties.


        :return: The gid of this NestNeuronProperties.
        :rtype: int
        """
        return self._gid

    @gid.setter
    def gid(self, gid: int):
        """Sets the gid of this NestNeuronProperties.


        :param gid: The gid of this NestNeuronProperties.
        :type gid: int
        """

        self._gid = gid

    @property
    def properties(self) -> object:
        """Gets the properties of this NestNeuronProperties.


        :return: The properties of this NestNeuronProperties.
        :rtype: object
        """
        return self._properties

    @properties.setter
    def properties(self, properties: object):
        """Sets the properties of this NestNeuronProperties.


        :param properties: The properties of this NestNeuronProperties.
        :type properties: object
        """

        self._properties = properties
