# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from access_node.models.base_model_ import Model
from access_node import util


class Precision(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DOUBLE = "double"
    INTEGER = "integer"

    def __init__(self):  # noqa: E501
        """Precision - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Precision':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Precision of this Precision.  # noqa: E501
        :rtype: Precision
        """
        return util.deserialize_model(dikt, cls)
