# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from access_node.models.base_model_ import Model
from access_node import util


class Spikes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, simulation_times: List[float]=None, neuron_ids: List[float]=None):  # noqa: E501
        """Spikes - a model defined in Swagger

        :param simulation_times: The simulation_times of this Spikes.  # noqa: E501
        :type simulation_times: List[float]
        :param neuron_ids: The neuron_ids of this Spikes.  # noqa: E501
        :type neuron_ids: List[float]
        """
        self.swagger_types = {
            'simulation_times': List[float],
            'neuron_ids': List[float]
        }

        self.attribute_map = {
            'simulation_times': 'simulation_times',
            'neuron_ids': 'neuron_ids'
        }

        self._simulation_times = simulation_times
        self._neuron_ids = neuron_ids

    @classmethod
    def from_dict(cls, dikt) -> 'Spikes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Spikes of this Spikes.  # noqa: E501
        :rtype: Spikes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def simulation_times(self) -> List[float]:
        """Gets the simulation_times of this Spikes.


        :return: The simulation_times of this Spikes.
        :rtype: List[float]
        """
        return self._simulation_times

    @simulation_times.setter
    def simulation_times(self, simulation_times: List[float]):
        """Sets the simulation_times of this Spikes.


        :param simulation_times: The simulation_times of this Spikes.
        :type simulation_times: List[float]
        """

        self._simulation_times = simulation_times

    @property
    def neuron_ids(self) -> List[float]:
        """Gets the neuron_ids of this Spikes.


        :return: The neuron_ids of this Spikes.
        :rtype: List[float]
        """
        return self._neuron_ids

    @neuron_ids.setter
    def neuron_ids(self, neuron_ids: List[float]):
        """Sets the neuron_ids of this Spikes.


        :param neuron_ids: The neuron_ids of this Spikes.
        :type neuron_ids: List[float]
        """

        self._neuron_ids = neuron_ids
