# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from access_node.models.base_model_ import Model
from access_node import util


class Spikes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, simulation_times: List[float]=None, gids: List[int]=None):  # noqa: E501
        """Spikes - a model defined in Swagger

        :param simulation_times: The simulation_times of this Spikes.  # noqa: E501
        :type simulation_times: List[float]
        :param gids: The gids of this Spikes.  # noqa: E501
        :type gids: List[int]
        """
        self.swagger_types = {
            'simulation_times': List[float],
            'gids': List[int]
        }

        self.attribute_map = {
            'simulation_times': 'simulation_times',
            'gids': 'gids'
        }

        self._simulation_times = simulation_times
        self._gids = gids

    @classmethod
    def from_dict(cls, dikt) -> 'Spikes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Spikes of this Spikes.  # noqa: E501
        :rtype: Spikes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def simulation_times(self) -> List[float]:
        """Gets the simulation_times of this Spikes.

        This array is always sorted.  # noqa: E501

        :return: The simulation_times of this Spikes.
        :rtype: List[float]
        """
        return self._simulation_times

    @simulation_times.setter
    def simulation_times(self, simulation_times: List[float]):
        """Sets the simulation_times of this Spikes.

        This array is always sorted.  # noqa: E501

        :param simulation_times: The simulation_times of this Spikes.
        :type simulation_times: List[float]
        """

        self._simulation_times = simulation_times

    @property
    def gids(self) -> List[int]:
        """Gets the gids of this Spikes.


        :return: The gids of this Spikes.
        :rtype: List[int]
        """
        return self._gids

    @gids.setter
    def gids(self, gids: List[int]):
        """Sets the gids of this Spikes.


        :param gids: The gids of this Spikes.
        :type gids: List[int]
        """

        self._gids = gids
