// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCHEMA_INSITE_NEST_H_
#define FLATBUFFERS_GENERATED_SCHEMA_INSITE_NEST_H_

#include "flatbuffers/flatbuffers.h"

namespace Insite {
namespace Nest {

struct Spikes;

struct SpikeTable;
struct SpikeTableBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Spikes FLATBUFFERS_FINAL_CLASS {
 private:
  double spike_time_;
  uint64_t node_id_;

 public:
  Spikes()
      : spike_time_(0),
        node_id_(0) {
  }
  Spikes(double _spike_time, uint64_t _node_id)
      : spike_time_(flatbuffers::EndianScalar(_spike_time)),
        node_id_(flatbuffers::EndianScalar(_node_id)) {
  }
  double spike_time() const {
    return flatbuffers::EndianScalar(spike_time_);
  }
  uint64_t node_id() const {
    return flatbuffers::EndianScalar(node_id_);
  }
};
FLATBUFFERS_STRUCT_END(Spikes, 16);

struct SpikeTable FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SpikeTableBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SPIKES = 4,
    VT_LAST_FRAME = 6
  };
  const flatbuffers::Vector<const Insite::Nest::Spikes *> *spikes() const {
    return GetPointer<const flatbuffers::Vector<const Insite::Nest::Spikes *> *>(VT_SPIKES);
  }
  bool last_frame() const {
    return GetField<uint8_t>(VT_LAST_FRAME, 0) != 0;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SPIKES) &&
           verifier.VerifyVector(spikes()) &&
           VerifyField<uint8_t>(verifier, VT_LAST_FRAME, 1) &&
           verifier.EndTable();
  }
};

struct SpikeTableBuilder {
  typedef SpikeTable Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_spikes(flatbuffers::Offset<flatbuffers::Vector<const Insite::Nest::Spikes *>> spikes) {
    fbb_.AddOffset(SpikeTable::VT_SPIKES, spikes);
  }
  void add_last_frame(bool last_frame) {
    fbb_.AddElement<uint8_t>(SpikeTable::VT_LAST_FRAME, static_cast<uint8_t>(last_frame), 0);
  }
  explicit SpikeTableBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SpikeTable> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SpikeTable>(end);
    return o;
  }
};

inline flatbuffers::Offset<SpikeTable> CreateSpikeTable(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<const Insite::Nest::Spikes *>> spikes = 0,
    bool last_frame = false) {
  SpikeTableBuilder builder_(_fbb);
  builder_.add_spikes(spikes);
  builder_.add_last_frame(last_frame);
  return builder_.Finish();
}

inline flatbuffers::Offset<SpikeTable> CreateSpikeTableDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<Insite::Nest::Spikes> *spikes = nullptr,
    bool last_frame = false) {
  auto spikes__ = spikes ? _fbb.CreateVectorOfStructs<Insite::Nest::Spikes>(*spikes) : 0;
  return Insite::Nest::CreateSpikeTable(
      _fbb,
      spikes__,
      last_frame);
}

inline const Insite::Nest::SpikeTable *GetSpikeTable(const void *buf) {
  return flatbuffers::GetRoot<Insite::Nest::SpikeTable>(buf);
}

inline const Insite::Nest::SpikeTable *GetSizePrefixedSpikeTable(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Insite::Nest::SpikeTable>(buf);
}

inline bool VerifySpikeTableBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Insite::Nest::SpikeTable>(nullptr);
}

inline bool VerifySizePrefixedSpikeTableBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Insite::Nest::SpikeTable>(nullptr);
}

inline void FinishSpikeTableBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Insite::Nest::SpikeTable> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSpikeTableBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Insite::Nest::SpikeTable> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Nest
}  // namespace Insite

#endif  // FLATBUFFERS_GENERATED_SCHEMA_INSITE_NEST_H_
